name: starter
description: This is a starter project that already has dark Mode and language support with provider implemented.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Themes
  flex_color_scheme: ^4.2.0
  stacked_themes: ^0.3.8+1
  
  # Font/Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.3
  

  # Tools
  sizer: ^2.0.15
  easy_localization: ^3.0.0

  # Device/Providers
  provider: ^6.0.2
  share_plus: ^3.0.5
  get: ^4.5.1
  get_storage: ^2.0.3
  share: ^2.0.4
  permission_handler: ^8.3.0
  path_provider: ^2.0.8
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.17
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  change_app_package_name: ^1.0.0
  flutter_automation: ^2.0.0
  lint: ^1.7.2


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/


# for changing app icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/"

# for changing splash screen
flutter_native_splash:
  image: assets/
  color: "ffffff"
  android_disable_fullscreen: true
  ios: true
  branding: assets/
  branding_mode: bottom
  android_gravity: center
  fullscreen: true